version: '2.1'

services: 
  demo-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=demo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
  spring-boot-jpa-docker-webapp:
    image: g00glen00b/spring-boot-jpa-docker-webapp
    depends_on:
      - demo-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=demo-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306